Replace Lua with LuaJIT and restrict loaded libraries for auto splitters
wins1ey/LAST pull request #34
Opened 2024-03-22 17:17 UTC by wins1ey

Restrict the loaded libraries to only base, string, math and jit. This is based on information from:
http://lua-users.org/wiki/SandBoxes

TODO:
- [ ] Further restrict the use of unsafe functions in the base library (e.g. setmetatable)
- [ ] Test current auto splitters with the changes

2024-03-26 20:53 UTC, Loomeh commented
Tony Hawk's Underground seemed to not work. It first made me switch out some logic (I had to change the '&' to 'and' on line 18).

The timer started correctly (loading works too) but LAST didn't split (which is weird considering it printed out the debug message for splitting)
```
Process: THUGONE.exe
PID: 4508
Refresh rate: 120
Started Manhattan; splitting timer...
```

2024-03-26 22:32 UTC, wins1ey commented
> The timer started correctly (loading works too) but LAST didn't split (which is weird considering it printed out the debug message for splitting)

Do you get the same issue with JSR? I quickly tested JSR and it was working as expected.
Perhaps this `story_flags[1] = true` is causing a problem and breaking the auto splitter?
What happens if you add another print statement after `return true`

2024-03-26 23:57 UTC, EXtremeExploit commented
> Tony Hawk's Underground seemed to not work. It first made me switch out some logic (I had to change the '&' to 'and' on line 18).
The & on that line is a bitwise operation, an "and" isnt the same logic, it will treat them like booleans

2024-03-27 00:03 UTC, wins1ey commented
The bit library is now available for auto splitters.
[Lua BitOp](https://bitop.luajit.org/)
[Lua BitOp API functions](https://bitop.luajit.org/api.html)
`local bit = require("bit")` isn't needed because the library is already loaded by LAST.

2024-03-27 00:47 UTC, EXtremeExploit commented
Just to have it in hand

Confirmed to work:
- [ ] AmidEvil.lua
- [ ] JSR.lua
- [x] MLP_AMBA.lua
- [ ] mec.lua
- [ ] mecadntp.lua
- [ ] thug.lua

2024-04-11 12:06 UTC, wins1ey commented
I think mec.lua and mecadntp.lua should work exactly the same as before since the only breaking change found in the auto splitters was the change in bitwise operations.

I'm happy to merge this if either of you approve.

2024-04-11 13:04 UTC, EXtremeExploit requested changes
just 1 small rename but other than that i see all is good, the change is fast

2024-04-11 13:04 UTC, EXtremeExploit commented on src/auto-splitter.c
> +static const char* functions[] = {
rename this to disabled_functions

2024-04-11 13:20 UTC, EXtremeExploit approved these changes

2024-04-11 13:31 UTC, merged

2024-04-13 13:25 UTC, Loomeh commented
Mirror's Edge Catalyst's auto splitter doesn't work. LAST complains about most of the readAddress variables returning the wrong return type (expected boolean).

Some logic seems to be working. It does print the debug message for loading, but nothing else works.

2024-04-13 14:38 UTC, wins1ey commented
Does #43 fix them?